<?php
/**
 * @category    Bubble
 * @package     Bubble_Highlighter
 * @version     1.0.1
 * @copyright   Copyright (c) 2015 BubbleShop (https://www.bubbleshop.net)
 */
/**
 * @var $this Bubble_Highlighter_Block_Adminhtml_Highlighter
 */
?>
<?php if ($this->isCodeMirrorEnabled()): ?>
<script type="text/javascript">
//<![CDATA[
var highlighter = new BubbleHighlighter({
    theme: '<?php echo $this->getTheme(); ?>',
    indentUnit: <?php echo $this->getIndentUnit(); ?>,
    lineNumbers: <?php echo $this->isLineNumbersEnabled(); ?>,
    lineWrapping: <?php echo $this->isLineWrappingEnabled(); ?>,
    autoCloseTags: <?php echo $this->isAutoCloseTagsEnabled(); ?>,
    wysiwygEnabled: <?php echo $this->isWysiwygEnabled(); ?>
});
Event.observe(window, 'load', function() {
    highlighter.find();
    if (typeof(Windows) != 'undefined') {
        Windows.addObserver({
            onShow: function () {
                highlighter.find();
            }
        });
    }
});
//]]>
</script>
<?php endif ?>