<?php
/**
 * @category    Bubble
 * @package     Bubble_Highlighter
 * @version     1.2.0
 * @copyright   Copyright (c) 2016 BubbleShop (https://www.bubbleshop.net)
 */
/**
 * @var $this Bubble_Highlighter_Block_Adminhtml_Highlighter
 */
?>
<?php if ($this->isCodeMirrorEnabled()): ?>
<script type="text/javascript">
//<![CDATA[
var highlighter = new BubbleHighlighter({
    theme: '<?php echo $this->getTheme(); ?>',
    indentUnit: <?php echo $this->getIndentUnit(); ?>,
    lineNumbers: <?php echo $this->isLineNumbersEnabled(); ?>,
    lineWrapping: <?php echo $this->isLineWrappingEnabled(); ?>,
    autoCloseTags: <?php echo $this->isAutoCloseTagsEnabled(); ?>,
    wysiwygEnabled: <?php echo $this->isWysiwygEnabled(); ?>
});
Event.observe(window, 'load', function() {
    highlighter.find();
    if (typeof(Windows) != 'undefined') {
        Windows.addObserver({
            onShow: function () {
                highlighter.find();
            }
        });
    }

    if ($('template_styles')) {
        var styleEditor = highlighter.create($('template_styles'), 'css');
        styleEditor.getWrapperElement().setStyle({ display: 'block' });
    }

    // Handle transactional emails editor
    if ($('template_text')) {
        var tplEditor = highlighter.create($('template_text'));
        tplEditor.getWrapperElement().setStyle({ display: 'block' });

        Ajax.Responders.register({
            onComplete: function() {
                if ($('template_text').value.length > 0) {
                    tplEditor.getDoc().setValue($('template_text').value);

                    if ($('template_styles')) {
                        styleEditor.getDoc().setValue($('template_styles').value);
                    }
                }
            }
        });
    }
});
//]]>
</script>
<?php endif ?>