<?php
/**
 * @category    Bubble
 * @package     Bubble_Highlighter
 * @version     1.1.2
 * @copyright   Copyright (c) 2015 BubbleShop (https://www.bubbleshop.net)
 */
/**
 * @var $this Bubble_Highlighter_Block_Adminhtml_Highlighter
 */
?>
<?php if ($this->isCodeMirrorEnabled()): ?>
<script type="text/javascript">
//<![CDATA[
var highlighter = new BubbleHighlighter({
    theme: '<?php echo $this->getTheme(); ?>',
    indentUnit: <?php echo $this->getIndentUnit(); ?>,
    lineNumbers: <?php echo $this->isLineNumbersEnabled(); ?>,
    lineWrapping: <?php echo $this->isLineWrappingEnabled(); ?>,
    autoCloseTags: <?php echo $this->isAutoCloseTagsEnabled(); ?>,
    wysiwygEnabled: <?php echo $this->isWysiwygEnabled(); ?>
});
Event.observe(window, 'load', function() {
    highlighter.find();
    if (typeof(Windows) != 'undefined') {
        Windows.addObserver({
            onShow: function () {
                highlighter.find();
            }
        });
    }

    if ($('template_styles')) {
        highlighter.create($('template_styles')).getWrapperElement().setStyle({ display: 'block' });
    }

    // Handle transactional emails editor
    if ($('template_text')) {
        highlighter.create($('template_text')).getWrapperElement().setStyle({ display: 'block' });

        Ajax.Responders.register({
            onComplete: function() {
                if ($('template_text').value.length > 0) {
                    if ($('template_text').hasClassName('bubble')) {
                        $('template_text').next().remove();
                        $('template_text').removeClassName('bubble')
                    }
                    highlighter.create($('template_text'));

                    if ($('template_styles')) {
                        if ($('template_styles').hasClassName('bubble')) {
                            $('template_styles').next().remove();
                            $('template_styles').removeClassName('bubble')
                        }
                        highlighter.create($('template_styles'));
                    }
                }
            }
        });
    }
});
//]]>
</script>
<?php endif ?>